### ISSUE TITLE
Dismiss dialog

### ISSUE THREAD

**Issue by Vibinreji** [BROUDING/SimpleDialog#2]
How to dismiss dialog? i tried hide() and dismiss()

**Comment by BROUDING** [comment]
```java
SimpleDialog mDialog = new SimpleDialog.Builder(thisActivity)
...

mDialog.dismiss();
```

This works like a charm for me.
Can you attach snippet of your code?

**Comment by Vibinreji** [comment]
Sorry..I did it in wrong way.Its working.Is there anyway to hide cancel button in progress dialog?
Thanks.

**Comment by BROUDING** [comment]
No worries,

I thought in UX (User experience) perspective, it's better to have a cancel button
in a potential-permanent dialog like this.
But if you're sure about you'll get the data in certain time,
```java
setBtnCancelShowTime(int btnCancelShowTime) // millisecond value
```
setting this value could be a trick.

But like I said, I don't really recommend this way.
User will close your app instead of canceling that call.

**Comment by Vibinreji** [comment]
Thank you:)
